pipeline {

     parameters {
        booleanParam(
            name: 'DESTROY',
            defaultValue: false,
            description: 'If true, Terraform DESTROY will run instead of APPLY'
        )
    }

    agent any

    environment {
        TERRAFORM_DIR = "terraform/environments/dev"
        ANSIBLE_DIR   = "ansible"
        INVENTORY_GEN = "ansible/scripts/generate_inventory.sh"
    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Init') {
            steps {
                dir(TERRAFORM_DIR) {
                    sh 'terraform init'
                }
            }
        }

        stage('Terraform Validate') {
            steps {
                dir(TERRAFORM_DIR) {
                    sh 'terraform validate'
                }
            }
        }

        stage('Terraform Apply / Destroy') {
    steps {
        script {
            if (params.DESTROY) {
                input message: '⚠️ Approve Terraform DESTROY? This will delete AWS resources'
                dir(TERRAFORM_DIR) {
                    sh 'terraform destroy -auto-approve'
                }
            } else {
                input message: 'Approve Terraform APPLY?'
                dir(TERRAFORM_DIR) {
                    sh 'terraform apply -auto-approve'
                }
            }
        }
    }
}

        stage('Generate Ansible Inventory') {
        
        when {
        expression { return !params.DESTROY }
            }
                
            steps {
                sh '''
                    chmod +x ${INVENTORY_GEN}
                    ${INVENTORY_GEN}
                '''
            }
        }

        stage('Ansible Configuration') {
    steps {
        sshagent(credentials: ['ec2-ap-south']) {
            dir('ansible') {
                sh '''
                  ansible-playbook site.yml \
                  -i inventories/dev/hosts.ini
                '''
            }
        }
    
}

        }
    }

    post {
        success {
            echo "✅ End-to-End DevOps platform deployed successfully"
        }
        failure {
            echo "❌ Pipeline failed — check logs"
        }
    }
    

}
