#############################################
# ArgoCD server
#############################################
- name: Install ArgoCD
  hosts: argocd
  become: true

  roles:
    - common
    - argocd


