---

#############################################
# Ensure required packages
#############################################
- name: Install base dependencies
  apt:
    name:
      - curl
      - unzip
    state: present
    update_cache: yes
  become: true

#############################################
# Install awscli (required for EKS)
#############################################
- name: Check awscli availability
  command: aws --version
  register: awscli_check
  failed_when: false
  changed_when: false

- name: Install awscli if missing
  shell: |
    curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
    unzip -o awscliv2.zip
    sudo ./aws/install
  when: awscli_check.rc != 0
  args:
    creates: /usr/local/bin/aws
  become: true

#############################################
# Ensure kubectl is available
#############################################
- name: Check kubectl availability
  command: kubectl version --client
  register: kubectl_check
  failed_when: false
  changed_when: false

- name: Install kubectl if missing
  get_url:
    url: https://dl.k8s.io/release/v1.29.0/bin/linux/amd64/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
  when: kubectl_check.rc != 0
  become: true

  vars:
   kubeconfig_path: /home/ubuntu/.kube/config

#############################################
# Configure kubeconfig for EKS
#############################################

- name: Ensure .kube directory exists
  file:
    path: /home/ubuntu/.kube
    state: directory
    owner: ubuntu
    group: ubuntu
    mode: '0755'
  become: true

- name: Configure kubeconfig for EKS
  command: >
    aws eks update-kubeconfig
    --region {{ aws_region }}
    --name {{ eks_cluster_name }}
    --kubeconfig {{ kubeconfig_path }}
  become: true
  become_user: ubuntu

#############################################
# Verify cluster connectivity (WITH RETRY)
#############################################

- name: Verify kubectl access to EKS (retry)
  command: kubectl get nodes
  register: kubectl_nodes
  retries: 5
  delay: 20
  until: kubectl_nodes.rc == 0
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

#############################################
# Ensure Namespace
#############################################

- name: Ensure argocd namespace exists
  command: kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false

#############################################
# Install ArgoCD
#############################################

- name: Install ArgoCD manifests
  command: >
    kubectl apply --server-side
    -n argocd
    -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    --validate=false
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"


#############################################
# Expose ArgoCD Server (NodePort)
#############################################
- name: Patch ArgoCD service to NodePort
  command: >
    kubectl patch svc argocd-server
    -n argocd
    -p '{"spec": {"type": "NodePort"}}'
  failed_when: false
  changed_when: false

#############################################
# Wait for ArgoCD server
#############################################

- name: Wait for ArgoCD rollout
  command: >
    kubectl rollout status deployment argocd-server -n argocd --timeout=600s
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"
  changed_when: false

- name: Verify kubectl access to EKS (retry)
  command: kubectl get nodes
  register: kubectl_nodes
  retries: 5
  delay: 20
  until: kubectl_nodes.rc == 0
  environment:
    KUBECONFIG: "{{ kubeconfig_path }}"

#############################################
# Get ArgoCD admin password
#############################################
- name: Get ArgoCD initial admin password
  command: >
    kubectl get secret argocd-initial-admin-secret
    -n argocd
    -o jsonpath="{.data.password}"
  register: argocd_password
  changed_when: false

- name: Decode ArgoCD admin password
  debug:
    msg: "ArgoCD admin password: {{ argocd_password.stdout | b64decode }}"
